### ISSUE TITLE
Consider a different tagline

### ISSUE THREAD

**Issue by milancurcic** [awvwgk/test-drive#1]
Thank you for starting this repo. I absolutely love the name "test-drive".

Consider changing the tagline. Currently you write "The non-fancy testing framework". But "non-fancy" could be interpreted as a negative. I suggest using a tagline "A simple testing framework". The word "simple" has the same meaning with what you intended, I think, but is a positive word.

It may seem like an irrelevant detail, but I think this matters a lot. It's the first thing that people will read coming to the repo and it sets the tone for the rest of their experience.

**Comment by awvwgk** [comment]
This part is just boilerplate I put together in a hurry. I changed to simple now, but I will probably revisit the overall presentation of the project later again.
